version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FlickrFeed"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-p054udptjrr4"
s3_prefix = "FlickrFeed"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
